const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
function harness(){const elements={};function el(id){return elements[id]??={innerHTML:'',textContent:'',style:{},classList:{add(){},remove(){}},addEventListener(){}};}const document={getElementById:el,querySelectorAll(){return [];}};const c=vm.createContext({document,window:{scrollTo(){}},location:{search:''},URLSearchParams,console,setTimeout,clearTimeout,setInterval,clearInterval});vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1].replace('\nboot();',''),c);c.state.practices=Array.from({length:6},(_,i)=>({id:'d'+i,date:'9/'+(i+1),time:'19:00-22:00',place:'検証用体育館',session:i===5?'am':'pm',capacity:2,capTrial:1}));c.state.roster=c.state.practices.map(p=>({id:p.id,members:['サンプル'],membersWait:[],trials:[],capMembers:2}));Object.assign(c.state,{fresh:true,hasProfile:true,session:'pm',mode:'',monthlyLimit:4,mine:[{practiceId:'d0',status:'confirmed'}],selected:{d0:true},myRemaining:{},myGuests:[],guests:[],expanded:{}});return {c,el};}
test('選択の追加は未送信と表示し、登録済みデータを変更しない',()=>{const {c,el}=harness();c.toggle('d1');assert.equal(c.state.mine.length,1);assert.match(el('root').innerHTML,/追加予定・未送信/);assert.match(el('selection-summary').innerHTML,/追加 1日・取消 0日/);});
test('登録済み日を外すと取消予定を表示し、戻すと未送信取消が消える',()=>{const {c,el}=harness();c.toggle('d0');assert.match(el('root').innerHTML,/取消予定・未送信/);assert.match(el('selection-summary').innerHTML,/取消 1日/);c.toggle('d0');assert.doesNotMatch(el('root').innerHTML,/取消予定・未送信/);});
test('朝夜の選択数を分けて表示し、別の部の選択も保持',()=>{const {c,el}=harness();c.toggle('d5');assert.match(el('selection-summary').innerHTML,/朝 1日 \/ 夜 1日/);c.clearSession();c.pickSession('am');assert.equal(c.state.selected.d0,true);assert.equal(c.state.selected.d5,true);});
test('月上限で5日目は選択されない',()=>{const {c,el}=harness();c.toggle('d1');c.toggle('d2');c.toggle('d3');c.toggle('d4');assert.equal(c.selectedInSession('pm'),4);assert.match(el('msg').innerHTML,/月に4回まで/);});
test('最新データを取得するまでは送信を有効化しない',()=>{const {c,el}=harness();c.state.fresh=false;c.updateSubmitBtn();assert.equal(el('submitBtn').disabled,true);});
test('日程は選択状態付きチェックボックスとして操作できる',()=>{const {c,el}=harness();c.render();assert.match(el('root').innerHTML,/role="checkbox" tabindex="0" aria-checked="true"/);assert.match(el('root').innerHTML,/aria-controls="rp-d0"/);});
test('体験入口はメンバーの月4回案内を表示しない',()=>{const {c,el}=harness();c.state.mode='trial';c.state.session=null;c.render();assert.match(el('root').innerHTML,/体験は1日/);assert.doesNotMatch(el('root').innerHTML,/月4回/);});
